#!/usr/bin/env python3
"""Run the local two-writer Hermes concurrency proof in a disposable repository."""

from __future__ import annotations

import copy
import importlib.util
import json
import os
from pathlib import Path
import subprocess
import sys
import tempfile
import time


FEATURE_ID = "e2e-parallel"
BACKEND_TASK_ID = "T-201"
FRONTEND_TASK_ID = "T-202"
CONFLICT_TASK_ID = "T-203"
MAXIMUM_WRITERS = 2
PROCESS_TIMEOUT_SECONDS = 10.0
LEASE_TTL_SECONDS = 60.0
BACKEND_FILE = "fixture/backend/src/main/java/example/Greeting.java"
FRONTEND_FILE = "fixture/frontend/app/page.tsx"
SHARED_FILE = "fixture/shared/release.txt"
RUNTIME_FILE = "sdd_runtime_guard.py"
JOB_EXECUTION_FILE = "sdd_job_execution.py"
WRITER_PROGRAM = r"""
import json
import os
from pathlib import Path
import sys
import time

ready, start_signal, target, result, label = map(Path, sys.argv[1:6])
ready.write_text("ready\n", encoding="utf-8")
while not start_signal.exists():
    time.sleep(0.002)
started = time.monotonic()
target.write_text(f"generated by {label.name}\n", encoding="utf-8")
time.sleep(0.15)
ended = time.monotonic()
result.write_text(
    json.dumps({"pid": os.getpid(), "start": started, "end": ended}),
    encoding="utf-8",
)
"""


def _load_runtime_module(filename: str, module_name: str):
    module_path = Path(__file__).parents[1] / "runtime" / filename
    if not module_path.is_file() or module_path.is_symlink():
        raise RuntimeError(f"canonical runtime module is unavailable: {filename}")
    existing = sys.modules.get(module_name)
    if existing is not None and Path(existing.__file__).resolve() == module_path.resolve():
        return existing
    spec = importlib.util.spec_from_file_location(module_name, module_path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"canonical runtime module cannot be loaded: {filename}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


runtime = _load_runtime_module(RUNTIME_FILE, "_sdd_e2e_parallel_runtime")
job_execution = _load_runtime_module(
    JOB_EXECUTION_FILE, "_sdd_e2e_parallel_job_execution"
)


class _GitAdapter:
    def __init__(self) -> None:
        self.branches: dict[str, str] = {}
        self.worktrees: dict[str, str] = {}

    def ensure_branch(self, *, branch: str, idempotency_key: str) -> str:
        return self.branches.setdefault(idempotency_key, branch)

    def ensure_worktree(
        self, *, path: str, branch: str, idempotency_key: str
    ) -> str:
        del branch
        return self.worktrees.setdefault(idempotency_key, path)


class _HermesAdapter:
    def __init__(self) -> None:
        self.sessions: dict[str, str] = {}

    def ensure_session(self, *, idempotency_key: str, worktree: str) -> str:
        del worktree
        task = idempotency_key.rsplit(":", 1)[1].lower()
        return self.sessions.setdefault(idempotency_key, f"session-{task}")


class _GitHubAdapter:
    def __init__(self) -> None:
        self.issues: dict[str, int] = {}
        self.pull_requests: dict[str, int] = {}

    def ensure_child_issue(
        self,
        *,
        parent_issue: int,
        feature_id: str,
        task_id: str,
        idempotency_key: str,
    ) -> int:
        del parent_issue, feature_id
        number = int(task_id.removeprefix("T-"))
        return self.issues.setdefault(idempotency_key, 1000 + number)

    def ensure_draft_pull_request(
        self, *, branch: str, issue: int, idempotency_key: str, draft: bool
    ) -> int:
        del branch, issue, draft
        number = int(idempotency_key.rsplit("T-", 1)[1])
        return self.pull_requests.setdefault(idempotency_key, 2000 + number)


class _KanbanAdapter:
    def __init__(self) -> None:
        self.identifiers: dict[str, dict[str, int]] = {}

    def record_external_ids(self, *, card_id: str, issue: int, pr: int) -> None:
        self.identifiers[card_id] = {"issue": issue, "pr": pr}


class _StateStore:
    def __init__(self) -> None:
        self.revision = 1
        self.external_ids: dict[str, dict[str, int]] = {}
        self.envelopes: dict[str, dict[str, object]] = {}

    def external_ids_for(self, *, task_id: str) -> dict[str, int] | None:
        value = self.external_ids.get(task_id)
        return None if value is None else copy.deepcopy(value)

    def compare_and_swap_task(
        self, *, expected_revision: int, task_id: str, issue: int, pr: int
    ) -> None:
        if expected_revision != self.revision:
            raise RuntimeError("stale local envelope revision")
        self.external_ids[task_id] = {"issue": issue, "pr": pr}
        self.revision += 1

    def envelope_for(self, *, idempotency_key: str) -> dict[str, object] | None:
        value = self.envelopes.get(idempotency_key)
        return None if value is None else copy.deepcopy(value)

    def record_envelope(
        self, *, idempotency_key: str, envelope: dict[str, object]
    ) -> None:
        existing = self.envelopes.get(idempotency_key)
        if existing is not None and existing != envelope:
            raise RuntimeError("divergent local envelope")
        self.envelopes[idempotency_key] = copy.deepcopy(envelope)


class _EventLog:
    def __init__(self) -> None:
        self.events: list[dict[str, object]] = []

    def record(self, **event: object) -> None:
        self.events.append(copy.deepcopy(event))


def _task_state(task_id: str, relative_file: str) -> dict[str, object]:
    return {
        "phase": "pending",
        "status": "pending",
        "dependencies": [],
        "test_ids": [f"{task_id}-T1"],
        "files_in_scope": [relative_file],
        "kanban_id": None,
        "issue": None,
        "branch": None,
        "pr": None,
        "red_at": None,
        "red_test_signature": None,
        "red_failure_excerpt": None,
        "green_at": None,
    }


def _scenario_state() -> dict[str, object]:
    return {
        "schema_version": 2,
        "feature_id": FEATURE_ID,
        "mode": "parallel",
        "project": "e2e-project",
        "board": "e2e-board",
        "max_workers": MAXIMUM_WRITERS,
        "revision": 1,
        "active_task": None,
        "tasks": {
            BACKEND_TASK_ID: _task_state(BACKEND_TASK_ID, BACKEND_FILE),
            FRONTEND_TASK_ID: _task_state(FRONTEND_TASK_ID, FRONTEND_FILE),
            CONFLICT_TASK_ID: _task_state(CONFLICT_TASK_ID, SHARED_FILE),
        },
    }


def _materialize_envelopes() -> dict[str, dict[str, object]]:
    git = _GitAdapter()
    hermes = _HermesAdapter()
    github = _GitHubAdapter()
    kanban = _KanbanAdapter()
    state_store = _StateStore()
    log = _EventLog()
    envelopes: dict[str, dict[str, object]] = {}
    for index, (task_id, slug) in enumerate(
        (
            (BACKEND_TASK_ID, "backend-writer"),
            (FRONTEND_TASK_ID, "frontend-writer"),
        ),
        start=1,
    ):
        card = f"card-{task_id.lower()}"
        envelope = job_execution.materialize_job(
            job={
                "feature_id": FEATURE_ID,
                "task_id": task_id,
                "slug": slug,
                "idempotency_key": f"{FEATURE_ID}:{task_id}",
                "kanban_id": card,
                "parent_issue": 900,
                "active_writer_count": MAXIMUM_WRITERS,
                "runtime_contract_merged": True,
                "synchronized_with_main": True,
                "state_revision": index,
            },
            git=git,
            hermes=hermes,
            github=github,
            kanban=kanban,
            state_store=state_store,
            log=log,
        )
        envelopes[task_id] = {
            "issue": envelope["issue"],
            "card": card,
            "branch": envelope["branch"],
            "worktree": envelope["worktree"],
            "session": envelope["session_id"],
            "pr": envelope["pr"],
        }
    return envelopes


def _acquire_lease(
    root: Path,
    state: dict[str, object],
    *,
    task_id: str,
    owner: str,
    session: str,
    relative_file: str,
) -> dict[str, object]:
    return runtime.acquire_scope_lease(
        root,
        feature_id=FEATURE_ID,
        task_id=task_id,
        owner=owner,
        session_id=session,
        files_in_scope=[relative_file],
        state=state,
        process_id=os.getpid(),
        process_start=runtime.process_start_token(os.getpid()),
        ttl_seconds=LEASE_TTL_SECONDS,
    )


def _release_lease(root: Path, lease: dict[str, object], owner: str, session: str) -> None:
    runtime.release_scope_lease(
        root,
        lease_id=str(lease["lease_id"]),
        owner=owner,
        session_id=session,
    )


def _launch_writer(
    *,
    ready: Path,
    start_signal: Path,
    target: Path,
    result: Path,
    label: str,
) -> subprocess.Popen[str]:
    return subprocess.Popen(
        [
            sys.executable,
            "-c",
            WRITER_PROGRAM,
            str(ready),
            str(start_signal),
            str(target),
            str(result),
            label,
        ],
        stdin=subprocess.DEVNULL,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
        start_new_session=True,
    )


def _wait_until_ready(paths: list[Path]) -> None:
    deadline = time.monotonic() + PROCESS_TIMEOUT_SECONDS
    while not all(path.is_file() for path in paths):
        if time.monotonic() >= deadline:
            raise RuntimeError("local writer readiness timed out")
        time.sleep(0.002)


def _collect_process(process: subprocess.Popen[str], result: Path) -> dict[str, object]:
    stdout, stderr = process.communicate(timeout=PROCESS_TIMEOUT_SECONDS)
    if process.returncode != 0:
        raise RuntimeError(f"local writer failed: {stderr or stdout}")
    evidence = json.loads(result.read_text(encoding="utf-8"))
    if evidence["pid"] != process.pid:
        raise RuntimeError("local writer process identity changed")
    return evidence


def _run_disjoint_writers(root: Path, temporary: Path) -> list[dict[str, object]]:
    specifications = (
        (BACKEND_TASK_ID, "backend", BACKEND_FILE),
        (FRONTEND_TASK_ID, "frontend", FRONTEND_FILE),
    )
    start_signal = temporary / "parallel.start"
    processes: list[tuple[str, str, str, subprocess.Popen[str], Path]] = []
    for task_id, stack, relative_file in specifications:
        ready = temporary / f"{stack}.ready"
        result = temporary / f"{stack}.json"
        process = _launch_writer(
            ready=ready,
            start_signal=start_signal,
            target=root / relative_file,
            result=result,
            label=stack,
        )
        processes.append((task_id, stack, relative_file, process, result))
    _wait_until_ready([temporary / "backend.ready", temporary / "frontend.ready"])
    start_signal.write_text("start\n", encoding="utf-8")
    return [
        {
            "task_id": task_id,
            "stack": stack,
            "files": [relative_file],
            **_collect_process(process, result),
        }
        for task_id, stack, relative_file, process, result in processes
    ]


def _run_one_writer(
    root: Path, temporary: Path, *, label: str, relative_file: str
) -> dict[str, object]:
    ready = temporary / f"{label}.ready"
    start_signal = temporary / f"{label}.start"
    result = temporary / f"{label}.json"
    start_signal.write_text("start\n", encoding="utf-8")
    process = _launch_writer(
        ready=ready,
        start_signal=start_signal,
        target=root / relative_file,
        result=result,
        label=label,
    )
    return _collect_process(process, result)


def _run_serialized_conflict(
    root: Path, temporary: Path, state: dict[str, object]
) -> dict[str, object]:
    first_owner = "conflict-a"
    first_session = "session-conflict-a"
    first_lease = _acquire_lease(
        root,
        state,
        task_id=CONFLICT_TASK_ID,
        owner=first_owner,
        session=first_session,
        relative_file=SHARED_FILE,
    )
    rejected = False
    try:
        try:
            _acquire_lease(
                root,
                state,
                task_id=CONFLICT_TASK_ID,
                owner="conflict-b",
                session="session-conflict-b",
                relative_file=SHARED_FILE,
            )
        except runtime.GuardError:
            rejected = True
        first = _run_one_writer(
            root, temporary, label="conflict-a", relative_file=SHARED_FILE
        )
    finally:
        _release_lease(root, first_lease, first_owner, first_session)

    second_owner = "conflict-b"
    second_session = "session-conflict-b"
    second_lease = _acquire_lease(
        root,
        state,
        task_id=CONFLICT_TASK_ID,
        owner=second_owner,
        session=second_session,
        relative_file=SHARED_FILE,
    )
    try:
        second = _run_one_writer(
            root, temporary, label="conflict-b", relative_file=SHARED_FILE
        )
    finally:
        _release_lease(root, second_lease, second_owner, second_session)
    return {
        "lease_rejected_while_active": rejected,
        "files": [SHARED_FILE],
        "intervals": [first, second],
    }


def _peak_concurrency(intervals: list[dict[str, object]]) -> int:
    events = [
        (float(interval[boundary]), 1 if boundary == "start" else -1)
        for interval in intervals
        for boundary in ("start", "end")
    ]
    active = 0
    peak = 0
    for _, change in sorted(events, key=lambda event: (event[0], -event[1])):
        active += change
        peak = max(peak, active)
    return peak


def run_parallel_scenario(repo_root: Path | str) -> dict[str, object]:
    """Execute disjoint writers and a serialized conflict using canonical guards."""

    root = runtime.repository_root(repo_root)
    state = _scenario_state()
    runtime.validate_state(state, repo_root=root, allow_legacy=False)
    envelopes = _materialize_envelopes()
    leases = [
        (
            owner,
            session,
            _acquire_lease(
                root,
                state,
                task_id=task_id,
                owner=owner,
                session=session,
                relative_file=relative_file,
            ),
        )
        for task_id, owner, session, relative_file in (
            (BACKEND_TASK_ID, "backend", "session-t-201", BACKEND_FILE),
            (FRONTEND_TASK_ID, "frontend", "session-t-202", FRONTEND_FILE),
        )
    ]
    try:
        with tempfile.TemporaryDirectory(prefix="hermes-parallel-processes-") as name:
            temporary = Path(name)
            writers = _run_disjoint_writers(root, temporary)
            for writer in writers:
                writer["envelope"] = envelopes[str(writer["task_id"])]
            overlap = min(float(writer["end"]) for writer in writers) - max(
                float(writer["start"]) for writer in writers
            )
    finally:
        for owner, session, lease in leases:
            _release_lease(root, lease, owner, session)

    with tempfile.TemporaryDirectory(prefix="hermes-parallel-conflict-") as name:
        conflict = _run_serialized_conflict(root, Path(name), state)
    return {
        "writers": writers,
        "overlap_seconds": overlap,
        "peak_writers": _peak_concurrency(writers),
        "maximum_writers": MAXIMUM_WRITERS,
        "conflict": conflict,
    }
