#!/usr/bin/env python3
"""Behavioral tests for the local full-stack parallel scenario."""

from __future__ import annotations

import importlib.util
import json
from pathlib import Path
import subprocess
import sys
import tempfile
import unittest


MODULE_PATH = Path(__file__).with_name("parallel_scenario.py")
BACKEND_FILE = "fixture/backend/src/main/java/example/Greeting.java"
FRONTEND_FILE = "fixture/frontend/app/page.tsx"
SHARED_FILE = "fixture/shared/release.txt"


def load_scenario():
    if not MODULE_PATH.is_file():
        raise AssertionError(
            "T-025-T1: parallel_scenario.py must run local full-stack writers"
        )
    spec = importlib.util.spec_from_file_location("parallel_scenario", MODULE_PATH)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def create_repository(temporary: str) -> Path:
    root = Path(temporary) / "repository"
    root.mkdir()
    subprocess.run(["git", "init", "-q", str(root)], check=True)
    subprocess.run(
        ["git", "-C", str(root), "config", "user.email", "e2e@example.test"],
        check=True,
    )
    subprocess.run(
        ["git", "-C", str(root), "config", "user.name", "Hermes E2E"],
        check=True,
    )
    for relative in (BACKEND_FILE, FRONTEND_FILE, SHARED_FILE):
        target = root / relative
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text("initial\n", encoding="utf-8")
    subprocess.run(["git", "-C", str(root), "add", "."], check=True)
    subprocess.run(
        ["git", "-C", str(root), "commit", "-qm", "fixture"], check=True
    )
    return root


class ParallelScenarioTest(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        cls.temporary = tempfile.TemporaryDirectory(prefix="sdd-parallel-e2e-")
        cls.root = create_repository(cls.temporary.name)
        cls.result = load_scenario().run_parallel_scenario(cls.root)

    @classmethod
    def tearDownClass(cls) -> None:
        cls.temporary.cleanup()

    def test_t025_t1_and_t2_launch_distinct_backend_and_frontend_processes(self) -> None:
        """T-025-T1/T-025-T2/AC-156: two local processes write disjoint stacks."""

        writers = self.result["writers"]
        self.assertEqual({"backend", "frontend"}, {item["stack"] for item in writers})
        self.assertEqual(2, len({item["pid"] for item in writers}))
        self.assertEqual({BACKEND_FILE, FRONTEND_FILE}, {item["files"][0] for item in writers})
        self.assertIn("generated by backend", (self.root / BACKEND_FILE).read_text())
        self.assertIn("generated by frontend", (self.root / FRONTEND_FILE).read_text())

    def test_t025_t3_intervals_have_strict_monotone_overlap(self) -> None:
        """T-025-T3/AC-219: measured monotone intervals overlap strictly."""

        writers = self.result["writers"]
        self.assertTrue(all(item["start"] < item["end"] for item in writers))
        expected = min(item["end"] for item in writers) - max(
            item["start"] for item in writers
        )
        self.assertGreater(expected, 0)
        self.assertEqual(expected, self.result["overlap_seconds"])

    def test_t025_t4_peak_is_exactly_two_and_never_exceeds_capacity(self) -> None:
        """T-025-T4/AC-227: active writer peak is exactly the canonical cap."""

        self.assertEqual(2, self.result["peak_writers"])
        self.assertEqual(2, self.result["maximum_writers"])
        self.assertLessEqual(
            self.result["peak_writers"], self.result["maximum_writers"]
        )

    def test_t025_t5_every_task_has_a_unique_complete_envelope(self) -> None:
        """T-025-T5/AC-219: isolated jobs own every lifecycle identity."""

        envelopes = [writer["envelope"] for writer in self.result["writers"]]
        for field in ("issue", "card", "branch", "worktree", "session", "pr"):
            values = [envelope[field] for envelope in envelopes]
            self.assertEqual(2, len(set(values)), field)
            self.assertTrue(all(values), field)

    def test_t025_t6_shared_scope_is_serialized_by_the_canonical_lease(self) -> None:
        """T-025-T6/AC-219: an overlapping path never runs concurrently."""

        conflict = self.result["conflict"]
        first, second = conflict["intervals"]
        self.assertTrue(conflict["lease_rejected_while_active"])
        self.assertLessEqual(first["end"], second["start"])
        self.assertEqual(SHARED_FILE, conflict["files"][0])
        self.assertIn(
            "generated by conflict-b", (self.root / SHARED_FILE).read_text()
        )

    def test_t025_t7_persistable_proof_is_relative_and_redacted(self) -> None:
        """T-025-T7/AC-219: published evidence contains no local path or secret."""

        encoded = json.dumps(self.result, sort_keys=True)
        self.assertNotIn(str(self.root), encoded)
        self.assertNotIn(self.temporary.name, encoded)
        self.assertNotIn("/Users/", encoded)
        self.assertNotIn("ghp_", encoded)
        self.assertNotIn("@example.test", encoded)

    def test_t025_contract_reuses_canonical_runtime_without_scheduler(self) -> None:
        """T-025-T2/T-025-T6: scenario imports canonical leases and envelopes."""

        source = MODULE_PATH.read_text(encoding="utf-8")
        self.assertIn("sdd_runtime_guard.py", source)
        self.assertIn("sdd_job_execution.py", source)
        self.assertNotIn("class Scheduler", source)
        self.assertNotIn("class Orchestrator", source)


if __name__ == "__main__":
    unittest.main()
